# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3268fab35f548ec20e6f925400836db4e6c3fbcf3ffb723a6ae1a7ec4e6e607abe47faf1f3a1138cfe2647ff6892b538470274c415504bba324528d3d4d27275

test:
  secret_key_base: 869e3e3f4b55ef207225bd99021a74f9d711d17b95d81c3393469d866cd03a51853cd7dc05dd2743ddd59cda55700f60c06b8017cb9907d6fc4fb1b1a6f86e56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
